on: [push, issue_comment, issues, pull_request, status]

jobs:
  actionman:
    runs-on: ubuntu-latest
    name: Actionman
    steps:
    - name: Run actionman
      id: actionman
      uses: lstoll/actionman@master
      env:
        ACTIONMAN_DEBUG: true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
