on: [push, issue_comment, issues, pull_request, status]

jobs:
  actionman:
    runs-on: ubuntu-latest
    name: Testing things out
    steps:
    - name: Run the action
      id: actionman
      uses: lstoll/actionman@master
      env:
        ACTIONMAN_DEBUG: true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get the output time
      run: echo "The time was ${{ steps.actionman.outputs.time }}"
